#include "MapDocument.h"
#include <pugixml.hpp>
#include <cmath>
#include <filesystem>
#include <iostream>
#include <vector>
static int Fail(int n) {std::cerr<<"FAIL NativeCollisionAuthoring checkpoint "<<n<<'\n';return n;}
static bool Eq(float a,float b) {return std::fabs(a-b)<.025f;}
static size_t Count(pugi::xml_node parent,const char* tag) {size_t n=0;for(auto x:parent.children(tag)){(void)x;++n;}return n;}
int main(int argc,char** argv) {
    auto path=std::filesystem::temp_directory_path()/"gtanks-native-collision-authoring-test.xml";
    auto path2=std::filesystem::temp_directory_path()/"gtanks-native-collision-authoring-test-2.xml";
    std::string error;
    MapDocument map;map.CreateBlank();
    const float x[]={4000,5000,4000},y[]={3500,3000,2500},yaw[]={0.f,4.712389f,9.424778f};
    for(int i=0;i<3;++i) {
        PropInstance p;p.library="Beach";p.group="sidewalls";p.name="Wall End 2";
        p.position={x[i],y[i],0};p.rotation.z=yaw[i];
        size_t index=map.AddProp(p);
        if(!map.AddVerifiedCollisionForProp(index))return Fail(1);
    }
    if(map.Props().size()!=3||map.CollisionPlanes().size()!=18||map.CollisionTriangles().size()!=30 ||
       map.CollisionBoxes().size()!=0)return Fail(2);
    if(!Eq(map.CollisionPlanes()[4].position.x,4000)||!Eq(map.CollisionPlanes()[4].position.y,3500))return Fail(3);
    if(!map.SaveLegacyAs(path,error)){std::cerr<<error<<'\n';return Fail(4);}
    pugi::xml_document native;
    if(!native.load_file(path.c_str()))return Fail(5);
    auto collision=native.child("map").child("collision-geometry");
    if(Count(collision,"collision-plane")!=18 || Count(collision,"collision-triangle")!=30)return Fail(6);
    if(!collision.child("collision-triangle").child("v0") || !collision.child("collision-plane").child("rotation"))return Fail(7);
    MapDocument reloaded;if(!reloaded.Load(path,error))return Fail(8);
    auto original=reloaded.CollisionTriangles()[10].position;
    auto position=reloaded.Props()[1].position,rotation=reloaded.Props()[1].rotation;
    position.x+=1000;rotation.z+=1.57079632679f;
    if(!reloaded.SetPropTransform(1,position,rotation))return Fail(9);
    // Authored triangle pivots around the whole prop; only its offset rotates.
    auto changed=reloaded.CollisionTriangles()[10].position;
    auto before=reloaded.Props()[1].position;
    if(Eq(original.x,changed.x) || !Eq(before.x,position.x))return Fail(10);
    if(!reloaded.SaveLegacyAs(path2,error)){std::cerr<<error<<'\n';return Fail(11);}
    MapDocument roundtrip;if(!roundtrip.Load(path2,error))return Fail(12);
    if(roundtrip.CollisionTriangles().size()!=30 ||
        !Eq(roundtrip.CollisionTriangles()[10].position.x,changed.x))return Fail(13);
    std::string reason;
    if(!roundtrip.DeletePropWithCollision(1,reason))return Fail(14);
    if(roundtrip.Props().size()!=2 || roundtrip.CollisionPlanes().size()!=12 ||
        roundtrip.CollisionTriangles().size()!=20)return Fail(15);
    if(!roundtrip.SaveLegacyAs(path2,error))return Fail(16);
    MapDocument final;if(!final.Load(path2,error) || final.CollisionPlanes().size()!=12 ||
        final.CollisionTriangles().size()!=20)return Fail(17);
    // A saved 0.5.12 visual-only wall can be repaired explicitly after reload,
    // but the action must not append the same native primitives twice.
    MapDocument visualOnly;visualOnly.CreateBlank();
    PropInstance oldWall;oldWall.library="Beach";oldWall.group="sidewalls";oldWall.name="Wall End 2";
    oldWall.position={10000,9000,600};visualOnly.AddProp(oldWall);
    if(!visualOnly.SaveLegacyAs(path,error))return Fail(27);
    MapDocument repaired;if(!repaired.Load(path,error)||repaired.HasVerifiedCollisionForProp(0))return Fail(28);
    if(!repaired.AddVerifiedCollisionForProp(0)||!repaired.HasVerifiedCollisionForProp(0)||
       repaired.AddVerifiedCollisionForProp(0))return Fail(29);
    if(!repaired.SaveLegacyAs(path,error))return Fail(30);
    MapDocument repairedReload;if(!repairedReload.Load(path,error)||
       !repairedReload.HasVerifiedCollisionForProp(0)||
       repairedReload.AddVerifiedCollisionForProp(0))return Fail(31);
    PropInstance unsupported;unsupported.library="Beach";unsupported.name="Unknown";
    auto id=final.AddProp(unsupported);
    if(final.AddVerifiedCollisionForProp(id) || final.CollisionTriangles().size()!=20)return Fail(18);
    // Independent fixture contains real native records transcribed from ten
    // original Beachfort placements, not values generated by our C++ writer.
    if(argc!=2)return Fail(19);
    MapDocument source;
    if(!source.Load(std::filesystem::path(argv[1]),error))return Fail(20);
    if(source.Props().size()!=10 || source.CollisionPlanes().size()!=60 ||
       source.CollisionTriangles().size()!=100)return Fail(21);
    auto sourceTriangle=source.CollisionTriangles()[10].position;
    auto sourcePosition=source.Props()[1].position;
    auto sourceRotation=source.Props()[1].rotation;
    sourcePosition.x+=1300;sourceRotation.z+=1.57079632679f;
    if(!source.SetPropTransform(1,sourcePosition,sourceRotation))return Fail(22);
    auto movedTriangle=source.CollisionTriangles()[10].position;
    if(Eq(sourceTriangle.x,movedTriangle.x)||Eq(sourceTriangle.y,movedTriangle.y))return Fail(23);
    if(!source.DeletePropWithCollision(1,reason)||source.CollisionPlanes().size()!=54 ||
       source.CollisionTriangles().size()!=90)return Fail(24);
    if(!source.SaveLegacyAs(path,error))return Fail(25);
    MapDocument fixtureReopened;
    if(!fixtureReopened.Load(path,error)||fixtureReopened.CollisionPlanes().size()!=54||
       fixtureReopened.CollisionTriangles().size()!=90)return Fail(26);
    std::error_code ec;std::filesystem::remove(path,ec);std::filesystem::remove(path2,ec);
    std::cout<<"Native collision 3x wall roundtrip, post-reload move/rotate and delete OK\n";
}
