"""Independent original-editor XML witnesses for transformed 3DS helper frames.

Fixtures are copied from the user's original GTanks library and unmodified
original map; expected XML is NOT generated by our MapDocument writer.
"""
import math
from pathlib import Path
import unittest
import xml.etree.ElementTree as ET
from test_native_helper_0515_audit import read_nodes

DIR=Path(__file__).parent/'fixtures/native_helpers'

def dot(a,b): return sum(x*y for x,y in zip(a,b))
def sub(a,b): return tuple(x-y for x,y in zip(a,b))
def vec(node,path): return tuple(float(node.findtext(f'{path}/{c}','0')) for c in 'xyz')
def project(node, visual):
    m=node['m']; axes=[m[i:i+3] for i in (0,3,6)]
    cols=[[dot(v,a) for v in node['v']] for a in axes]
    lo=[min(c) for c in cols];hi=[max(c) for c in cols]
    center=tuple(sum(axes[k][i]*(lo[k]+hi[k])*.5 for k in range(3)) for i in range(3))
    va=[visual['m'][i:i+3] for i in (0,3,6)]
    local=tuple(dot(sub(center,visual['m'][9:]),a) for a in va)
    size=tuple(hi[i]-lo[i] for i in range(3))
    axis=axes[0]
    relative=(dot(axis,va[0]),dot(axis,va[1]))
    rotation=math.atan2(relative[1],relative[0])
    return local,size,rotation

class OriginalNativeFramesAudit(unittest.TestCase):
    def check_original(self,file,visual_name,xml_name):
        nodes=read_nodes(DIR/file);visual=nodes[visual_name]
        root=ET.parse(DIR/xml_name).getroot();prop=root.find('./static-geometry/prop')
        self.assertIsNotNone(prop)
        position=vec(prop,'position');yaw=float(prop.findtext('rotation/z','0'))
        expected=list(root.findall('./collision-geometry/collision-box'))
        imported=[project(n,visual) for name,n in nodes.items() if name.lower().startswith('box')]
        self.assertEqual(len(imported),len(expected))
        matched=set()
        for local,size,rot in imported:
            world=(position[0]+math.cos(yaw)*local[0]-math.sin(yaw)*local[1],
                   position[1]+math.sin(yaw)*local[0]+math.cos(yaw)*local[1],
                   position[2]+local[2])
            matches=[]
            for i,box in enumerate(expected):
                if (all(abs(a-b)<.012 for a,b in zip(world,vec(box,'position'))) and
                    all(abs(a-b)<.012 for a,b in zip(size,vec(box,'size'))) and
                    abs(math.atan2(math.sin(rot+yaw-float(box.findtext('rotation/z','0'))),
                                   math.cos(rot+yaw-float(box.findtext('rotation/z','0')))))<.003):
                    matches.append(i)
            self.assertEqual(len(matches),1,(file,world,size,rot,matches))
            matched.add(matches[0])
        self.assertEqual(len(matched),len(expected))
    def test_rotated_visual_frame_waffle_wall(self):
        self.check_original('waffle_wall_1.3ds','wall_1','waffle_wall1_original_map.xml')
    def test_rotated_box_frame_billboard(self):
        self.check_original('promotion_bilboard.3ds','bilboard','billboard_original_map.xml')
    def test_source_has_frame_validation_and_world_local_conversion(self):
        src=(DIR.parents[2]/'src/NativeCollisionImport.h').read_text(encoding='utf8')
        for token in ('const auto toLocal=', 'const auto dirToLocal=',
                      'Dot(v,axes[at])', 'out.rotation=Euler(bx,by,bz)',
                      'Unverified scale/shear/mirror'):
            self.assertIn(token,src)
if __name__=='__main__':unittest.main()
