"""Independent 3DS vertices/face orientation vs original GTanks Editor XML.

The reference XML was extracted from the user's in-game-tested Wall End 1 map,
not generated by ProTanki's serialization code. No network or Windows runtime.
"""
import math
from pathlib import Path
import struct
import unittest
import xml.etree.ElementTree as ET

ROOT=Path(__file__).resolve().parent.parent
FIX=ROOT/'tests/fixtures/native_helpers'

def vec(n,name):
    x=n.find(name)
    return tuple(float(x.findtext(c,'0')) for c in 'xyz')

def sub(a,b):return tuple(x-y for x,y in zip(a,b))
def add(a,b):return tuple(x+y for x,y in zip(a,b))
def cross(a,b):return (a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0])
def dot(a,b):return sum(x*y for x,y in zip(a,b))
def norm(a):return math.sqrt(dot(a,a))
def unit(a):return tuple(x/norm(a) for x in a)
def rotation(v,angles):
    ax,ay,az=angles
    cx,sx=math.cos(ax),math.sin(ax);cy,sy=math.cos(ay),math.sin(ay);cz,sz=math.cos(az),math.sin(az)
    x=(v[0],cx*v[1]-sx*v[2],sx*v[1]+cx*v[2])
    y=(cy*x[0]+sy*x[2],x[1],-sy*x[0]+cy*x[2])
    return (cz*y[0]-sz*y[1],sz*y[0]+cz*y[1],y[2])

def read_nodes(path):
    raw=path.read_bytes();out={}
    def walk(a,b,name=''):
        while a+6<=b:
            t,l=struct.unpack_from('<HI',raw,a)
            if l<6 or a+l>b:raise ValueError('Malformed 3DS chunk')
            x,y=a+6,a+l
            if t==0x4000:
                z=raw.index(0,x,y);n=raw[x:z].decode('latin1');out[n]={'v':[],'f':[],'m':[]};walk(z+1,y,n)
            elif t==0x4110:
                c=struct.unpack_from('<H',raw,x)[0];out[name]['v']=[struct.unpack_from('<fff',raw,x+2+i*12) for i in range(c)]
            elif t==0x4120:
                c=struct.unpack_from('<H',raw,x)[0];out[name]['f']=[struct.unpack_from('<HHHH',raw,x+2+i*8)[:3] for i in range(c)]
            elif t==0x4160:out[name]['m']=struct.unpack_from('<12f',raw,x)
            elif t in (0x4d4d,0x3d3d,0x4100):walk(x,y,name)
            a=y
    walk(0,len(raw));return out

def same_set(want,actual,tolerance=.012):
    remaining=list(actual)
    for vertex in want:
        match=next((i for i,p in enumerate(remaining) if norm(sub(vertex,p))<tolerance),None)
        if match is None:return False
        remaining.pop(match)
    return not remaining

class OriginalNativeGeometryAudit(unittest.TestCase):
    def test_real_wall_3ds_helpers_equal_all_original_native_shapes(self):
        nodes=read_nodes(FIX/'wall_e1.3ds')
        doc=ET.parse(FIX/'concrete_wall_end1_original_map.xml').getroot()
        prop=doc.find('static-geometry/prop');self.assertIsNotNone(prop)
        self.assertEqual((prop.get('library-name'),prop.get('name')),('Concrete Walls','Wall End 1'))
        pivot=nodes['wall_e1']['m'][-3:];place=vec(prop,'position');yaw=float(prop.findtext('rotation/z'))
        shapes=list(doc.find('collision-geometry'));self.assertEqual(len(shapes),16)
        matching=set()
        for name,node in nodes.items():
            is_plane=name.lower().startswith('plane');is_tri=name.lower().startswith('tri')
            if not (is_plane or is_tri):continue
            expected=[add(place,rotation(sub(p,pivot),(0,0,yaw))) for p in node['v']]
            face=node['f'][0];expected_normal=unit(cross(sub(expected[face[1]],expected[face[0]]),sub(expected[face[2]],expected[face[0]])))
            result=[]
            for index,sh in enumerate(shapes):
                if sh.tag!=('collision-plane' if is_plane else 'collision-triangle'):continue
                center=vec(sh,'position');rot=vec(sh,'rotation')
                if is_plane:
                    width=float(sh.findtext('width'));length=float(sh.findtext('length'))
                    local=[(i*width/2,j*length/2,0) for i,j in ((-1,-1),(1,-1),(-1,1),(1,1))]
                    signed_normal=rotation((0,0,1),rot)
                else:
                    local=[vec(sh,'v'+str(i)) for i in range(3)]
                    world=[add(center,rotation(v,rot)) for v in local]
                    signed_normal=unit(cross(sub(world[1],world[0]),sub(world[2],world[0])))
                world=[add(center,rotation(v,rot)) for v in local]
                if same_set(expected,world) and dot(expected_normal,signed_normal)>.9999:result.append(index)
            self.assertEqual(len(result),1, f'{name} has ambiguous/missing original native shape: {result}')
            matching.add(result[0])
        self.assertEqual(len(matching),16)

    def test_fail_closed_authoring_and_no_false_glb_game_export(self):
        ui=(ROOT/'src/EditorUi.cpp').read_text(encoding='utf8')
        header=(ROOT/'src/EditorUi.h').read_text(encoding='utf8')
        importer=(ROOT/'src/NativeCollisionImport.h').read_text(encoding='utf8')
        self.assertIn('bool allowVisualOnlyPlacement_{};',header)
        self.assertIn('map.AddImportedCollisionForProp(index,imported)',ui)
        self.assertIn('Native helper collision refused',ui)
        self.assertIn('GLB: collision draft',ui)
        self.assertIn('Edit solid/trigger boxes below.',ui)
        self.assertIn('There is no native 3DS or ProTLVK game export yet.',ui)
        self.assertIn('Unverified scale/shear/mirror in 3DS visual pivot',importer)
        self.assertIn('Missing box corners:',importer)
        self.assertIn('result.boxes.push_back(out)',importer)

if __name__=='__main__':unittest.main()
